name: Tests

on:
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: 
          - 14.x

    steps:
      - name: Checkouting code...
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: NPM install
        run: npm install

      - name: NPM build
        run: npm build

      - name: NPM format check
        run: npm run format-check

      - name: NPM format
        run: npm run format

      - name: Lint
        run: npm run lint

      - name: Pack
        run: npm run pack